# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76df9f5264dc7d2b01f12aa9fe9b895831bf5355e76cb904c7533c792ccda90ebedd25b8c11426417c4ace9c888c701861243b975e6f9ad6513268053c4cc232

test:
  secret_key_base: f12972fb9531912f5b62d4c16cb8f76061bc74975b02e75e0a0510841300bb18572809543a265009d0a437f7a60bb096c1ad140ec5c1b8f0a460d6d9311a8f9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
